# Generated by Django 3.1.6 on 2021-04-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverdetail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverRegistration',
            new_name='Driver_Registration',
        ),
    ]
